m=input("enter string")
c=m.count('a')
d=m.count('e')
e=m.count('i')
f=m.count('o')
w=m.count('u')
x=m.count('A')
y=m.count('E')
z=m.count('I')
n=m.count('O')
q=m.count('U')
p=c+d+e+f+w+x+y+z+n+q
print("your vowells is:",p)
